name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: latest
      - run: uv build
      - uses: actions/upload-artifact@v4
        with:
          name: uv-build
          path: dist/
          if-no-files-found: error
          compression-level: 0