name: Publish

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: latest
      - run: uv build
      - uses: actions/upload-artifact@v4
        with:
          name: uv-build
          path: dist/
          if-no-files-found: error
          compression-level: 0
  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    environment:
      name: release
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: latest
      - uses: actions/download-artifact@v4
        with:
          name: uv-build
          path: dist/
          if-no-files-found: error
      - run: uv publish --publish-url https://test.pypi.org/legacy/
      - run: uv publish
